name: Set elevator to usable but dangerous
on:
  issues:
    types: [closed]

jobs:
  build:
    name: Elevator to usable but dangerous
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "Zenika Nantes Elevator bot"
          git config user.email "<>"
      
      - name: Update elevator state
        run: |
          sed -i 's/Non/Fonctionne mais dangereux/' index.html
          git add .
          git commit -m "⚠️ set elevator to usable but dangerous"
          git push origin main
