name: Set evelvator to unusable
on:
  issues:
    types:
      - [opened]

jobs:
  build:
    name: Evelvator to unusable
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "Zenika Nantes Evevator bot"
          git config user.email "<>"
      
      - name: Update elevator state
        run: |
          $VAL=$(cat variables.js)
          echo "${VAL/Oui/Non}" > variables.js
          git add .
          git commit -m "set evelvator to unusable"
          git push origin main